options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # STEP 1 
  # using code build internal command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','pradipwebapp:v1', '.']
  
  # STEP 2
  # do SAST in build container image with trivy
  - name: 'aquasec/trivy:latest'
    # args: ['image' , 'pradipwebapp:v1']
    args: ['image' ,'--severity' ,'HIGH,CRITICAL' ,'--format', 'json',  '--output' , '/workspace/pradip_imagescan.json','--exit-code','0','pradipwebapp:v1']
  

  # STEP 3 upload trivy result to GSC 
  - name:  'google/cloud-sdk'
    args: ['gsutil', 'cp','/workspace/pradip_imagescan.json','gs://vodafone-trivy-scan-results/containers/']
    
  # Step 4
  # creating container 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'pradip11',
     '-p' ,'2300:80' ,'pradipwebapp:v1'
    ]
  
  # step 5  app running status by loging into same container and doing curl 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec','pradip11','curl','-f','http://localhost/health.html']
  
  # step 6  push images into artifact registry

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/pradipwebapp:v1']

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'REGION-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/your-image-name:latest', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'REGION-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/your-image-name:latest']
