options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # STEP 1 
  # using code build internal command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','pradipwebapp:v1', '.']
  # Step 2 
  # creating container 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'pradip11',
     '-p' ,'2300:80', '--rm' ,'pradipwebapp:v1'
    ]

