apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pradip-app-deploy
  name: pradip-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pradip-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pradip-app-deploy
    spec:
      containers:
      - image: asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/pradipwebapp:v1
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}